name: Docker Image "pod5-conversion" CI

on:
  workflow_dispatch:
  schedule:
    - cron: '11 0 */7 * *'
  push:
    paths:
      - base/**
      - Dockerfile
      - run.sh

jobs:
  build-and-push:
    runs-on: hk

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: cuhkhaosun/pod5-conversion:latest
        platforms: linux/amd64

    - name: Run pod5 conversion script
      run: |
        docker run --name pod5-conversion-container -v "${{ github.workspace }}/data:/data" cuhkhaosun/pod5-conversion:latest /entrypoint.sh
      env:
        output_dir: /data/output_pod5s
